// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: condition.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Gserver {

  /// <summary>Holder for reflection information generated from condition.proto</summary>
  public static partial class ConditionReflection {

    #region Descriptor
    /// <summary>File descriptor for condition.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConditionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9jb25kaXRpb24ucHJvdG8SB2dzZXJ2ZXIqewoNQ29uZGl0aW9uVHlwZRIW",
            "ChJDb25kaXRpb25UeXBlX05vbmUQABInCiNDb25kaXRpb25UeXBlX1BsYXll",
            "clByb3BlcnR5Q29tcGFyZRABEikKJUNvbmRpdGlvblR5cGVfQWN0aXZpdHlQ",
            "cm9wZXJ0eUNvbXBhcmUQAkIGWgQuL3BiYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Gserver.ConditionType), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 条件类型
  /// </summary>
  public enum ConditionType {
    /// <summary>
    /// 解决"The first enum value must be zero in proto3."的报错
    /// </summary>
    [pbr::OriginalName("ConditionType_None")] None = 0,
    /// <summary>
    /// 玩家属性值比较
    /// </summary>
    [pbr::OriginalName("ConditionType_PlayerPropertyCompare")] PlayerPropertyCompare = 1,
    /// <summary>
    /// 活动属性值比较
    /// </summary>
    [pbr::OriginalName("ConditionType_ActivityPropertyCompare")] ActivityPropertyCompare = 2,
  }

  #endregion

}

#endregion Designer generated code
