// Code generated by proto_code_gen. DO NOT EDIT
// github.com/fish-tennis/proto_code_gen
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using Google.Protobuf;
using Google.Protobuf.Reflection;

namespace Gserver {
	public static partial class GlobalFileDescriptorSet {
		public static List<FileDescriptor> Descriptors {
		  get { return fileDescriptors; }
		}
		private static List<FileDescriptor> fileDescriptors;
		static GlobalFileDescriptorSet() {
			fileDescriptors = new List<FileDescriptor>();
			
			fileDescriptors.Add(AccountReflection.Descriptor);
			
			fileDescriptors.Add(ActivityReflection.Descriptor);
			
			fileDescriptors.Add(BagsReflection.Descriptor);
			
			fileDescriptors.Add(BaseinfoReflection.Descriptor);
			
			fileDescriptors.Add(CfgReflection.Descriptor);
			
			fileDescriptors.Add(ClientBaseReflection.Descriptor);
			
			fileDescriptors.Add(ExchangeReflection.Descriptor);
			
			fileDescriptors.Add(GlobalEntityReflection.Descriptor);
			
			fileDescriptors.Add(GuildReflection.Descriptor);
			
			fileDescriptors.Add(ItemReflection.Descriptor);
			
			fileDescriptors.Add(LoginReflection.Descriptor);
			
			fileDescriptors.Add(MoneyReflection.Descriptor);
			
			fileDescriptors.Add(PlayerReflection.Descriptor);
			
			fileDescriptors.Add(ProgressReflection.Descriptor);
			
			fileDescriptors.Add(QuestReflection.Descriptor);
			
			fileDescriptors.Add(RouteReflection.Descriptor);
			
			fileDescriptors.Add(ServerBaseReflection.Descriptor);
			
		}
	}
}
