// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: error_code.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Gserver {

  /// <summary>Holder for reflection information generated from error_code.proto</summary>
  public static partial class ErrorCodeReflection {

    #region Descriptor
    /// <summary>File descriptor for error_code.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ErrorCodeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBlcnJvcl9jb2RlLnByb3RvEgdnc2VydmVyKuYBCglFcnJvckNvZGUSEAoM",
            "RXJyb3JDb2RlX09LEAASFAoQRXJyb3JDb2RlX05vdFJlZxALEhsKF0Vycm9y",
            "Q29kZV9QYXNzd29yZEVycm9yEAwSEwoPRXJyb3JDb2RlX0RiRXJyEA0SGwoX",
            "RXJyb3JDb2RlX05hbWVEdXBsaWNhdGUQDhIWChJFcnJvckNvZGVfSGFzTG9n",
            "aW4QDxIaChZFcnJvckNvZGVfU2Vzc2lvbkVycm9yEBASFgoSRXJyb3JDb2Rl",
            "X05vUGxheWVyEBESFgoSRXJyb3JDb2RlX1RyeUxhdGVyEBJCBloELi9wYmIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Gserver.ErrorCode), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ErrorCode {
    [pbr::OriginalName("ErrorCode_OK")] Ok = 0,
    /// <summary>
    /// 未注册
    /// </summary>
    [pbr::OriginalName("ErrorCode_NotReg")] NotReg = 11,
    /// <summary>
    /// 密码错误
    /// </summary>
    [pbr::OriginalName("ErrorCode_PasswordError")] PasswordError = 12,
    /// <summary>
    /// 数据库错误
    /// </summary>
    [pbr::OriginalName("ErrorCode_DbErr")] DbErr = 13,
    /// <summary>
    /// 重名
    /// </summary>
    [pbr::OriginalName("ErrorCode_NameDuplicate")] NameDuplicate = 14,
    [pbr::OriginalName("ErrorCode_HasLogin")] HasLogin = 15,
    [pbr::OriginalName("ErrorCode_SessionError")] SessionError = 16,
    [pbr::OriginalName("ErrorCode_NoPlayer")] NoPlayer = 17,
    [pbr::OriginalName("ErrorCode_TryLater")] TryLater = 18,
  }

  #endregion

}

#endregion Designer generated code
