// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: route.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Gserver {

  /// <summary>Holder for reflection information generated from route.proto</summary>
  public static partial class RouteReflection {

    #region Descriptor
    /// <summary>File descriptor for route.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RouteReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgtyb3V0ZS5wcm90bxIHZ3NlcnZlchoZZ29vZ2xlL3Byb3RvYnVmL2FueS5w",
            "cm90byKsAQoSUm91dGVQbGF5ZXJNZXNzYWdlEg0KBWVycm9yGAEgASgJEhIK",
            "CnRvUGxheWVySWQYAiABKAMSFQoNcGFja2V0Q29tbWFuZBgDIAEoBRIYChBk",
            "aXJlY3RTZW5kQ2xpZW50GAQgASgIEhgKEHBlbmRpbmdNZXNzYWdlSWQYBSAB",
            "KAMSKAoKcGFja2V0RGF0YRgGIAEoCzIULmdvb2dsZS5wcm90b2J1Zi5Bbnki",
            "tgEKGkd1aWxkUm91dGVQbGF5ZXJNZXNzYWdlUmVxEhQKDGZyb21QbGF5ZXJJ",
            "ZBgBIAEoAxITCgtmcm9tR3VpbGRJZBgCIAEoAxIUCgxmcm9tU2VydmVySWQY",
            "AyABKAUSFgoOZnJvbVBsYXllck5hbWUYBCABKAkSFQoNcGFja2V0Q29tbWFu",
            "ZBgFIAEoBRIoCgpwYWNrZXREYXRhGAYgASgLMhQuZ29vZ2xlLnByb3RvYnVm",
            "LkFueUIGWgQuL3BiYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Gserver.RoutePlayerMessage), global::Gserver.RoutePlayerMessage.Parser, new[]{ "Error", "ToPlayerId", "PacketCommand", "DirectSendClient", "PendingMessageId", "PacketData" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Gserver.GuildRoutePlayerMessageReq), global::Gserver.GuildRoutePlayerMessageReq.Parser, new[]{ "FromPlayerId", "FromGuildId", "FromServerId", "FromPlayerName", "PacketCommand", "PacketData" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 路由转发给玩家的消息
  /// server -> otherserver -> player
  /// </summary>
  public sealed partial class RoutePlayerMessage : pb::IMessage<RoutePlayerMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RoutePlayerMessage> _parser = new pb::MessageParser<RoutePlayerMessage>(() => new RoutePlayerMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RoutePlayerMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Gserver.RouteReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoutePlayerMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoutePlayerMessage(RoutePlayerMessage other) : this() {
      error_ = other.error_;
      toPlayerId_ = other.toPlayerId_;
      packetCommand_ = other.packetCommand_;
      directSendClient_ = other.directSendClient_;
      pendingMessageId_ = other.pendingMessageId_;
      packetData_ = other.packetData_ != null ? other.packetData_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoutePlayerMessage Clone() {
      return new RoutePlayerMessage(this);
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 1;
    private string error_ = "";
    /// <summary>
    /// 错误码
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "toPlayerId" field.</summary>
    public const int ToPlayerIdFieldNumber = 2;
    private long toPlayerId_;
    /// <summary>
    /// 玩家id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ToPlayerId {
      get { return toPlayerId_; }
      set {
        toPlayerId_ = value;
      }
    }

    /// <summary>Field number for the "packetCommand" field.</summary>
    public const int PacketCommandFieldNumber = 3;
    private int packetCommand_;
    /// <summary>
    /// 消息号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PacketCommand {
      get { return packetCommand_; }
      set {
        packetCommand_ = value;
      }
    }

    /// <summary>Field number for the "directSendClient" field.</summary>
    public const int DirectSendClientFieldNumber = 4;
    private bool directSendClient_;
    /// <summary>
    /// 是否直接转发给客户端
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool DirectSendClient {
      get { return directSendClient_; }
      set {
        directSendClient_ = value;
      }
    }

    /// <summary>Field number for the "pendingMessageId" field.</summary>
    public const int PendingMessageIdFieldNumber = 5;
    private long pendingMessageId_;
    /// <summary>
    /// 待处理消息id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PendingMessageId {
      get { return pendingMessageId_; }
      set {
        pendingMessageId_ = value;
      }
    }

    /// <summary>Field number for the "packetData" field.</summary>
    public const int PacketDataFieldNumber = 6;
    private global::Google.Protobuf.WellKnownTypes.Any packetData_;
    /// <summary>
    /// 转发的消息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Any PacketData {
      get { return packetData_; }
      set {
        packetData_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RoutePlayerMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RoutePlayerMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Error != other.Error) return false;
      if (ToPlayerId != other.ToPlayerId) return false;
      if (PacketCommand != other.PacketCommand) return false;
      if (DirectSendClient != other.DirectSendClient) return false;
      if (PendingMessageId != other.PendingMessageId) return false;
      if (!object.Equals(PacketData, other.PacketData)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      if (ToPlayerId != 0L) hash ^= ToPlayerId.GetHashCode();
      if (PacketCommand != 0) hash ^= PacketCommand.GetHashCode();
      if (DirectSendClient != false) hash ^= DirectSendClient.GetHashCode();
      if (PendingMessageId != 0L) hash ^= PendingMessageId.GetHashCode();
      if (packetData_ != null) hash ^= PacketData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Error.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Error);
      }
      if (ToPlayerId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ToPlayerId);
      }
      if (PacketCommand != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(PacketCommand);
      }
      if (DirectSendClient != false) {
        output.WriteRawTag(32);
        output.WriteBool(DirectSendClient);
      }
      if (PendingMessageId != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(PendingMessageId);
      }
      if (packetData_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(PacketData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Error.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Error);
      }
      if (ToPlayerId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ToPlayerId);
      }
      if (PacketCommand != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(PacketCommand);
      }
      if (DirectSendClient != false) {
        output.WriteRawTag(32);
        output.WriteBool(DirectSendClient);
      }
      if (PendingMessageId != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(PendingMessageId);
      }
      if (packetData_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(PacketData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      if (ToPlayerId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ToPlayerId);
      }
      if (PacketCommand != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PacketCommand);
      }
      if (DirectSendClient != false) {
        size += 1 + 1;
      }
      if (PendingMessageId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PendingMessageId);
      }
      if (packetData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PacketData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RoutePlayerMessage other) {
      if (other == null) {
        return;
      }
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      if (other.ToPlayerId != 0L) {
        ToPlayerId = other.ToPlayerId;
      }
      if (other.PacketCommand != 0) {
        PacketCommand = other.PacketCommand;
      }
      if (other.DirectSendClient != false) {
        DirectSendClient = other.DirectSendClient;
      }
      if (other.PendingMessageId != 0L) {
        PendingMessageId = other.PendingMessageId;
      }
      if (other.packetData_ != null) {
        if (packetData_ == null) {
          PacketData = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        PacketData.MergeFrom(other.PacketData);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Error = input.ReadString();
            break;
          }
          case 16: {
            ToPlayerId = input.ReadInt64();
            break;
          }
          case 24: {
            PacketCommand = input.ReadInt32();
            break;
          }
          case 32: {
            DirectSendClient = input.ReadBool();
            break;
          }
          case 40: {
            PendingMessageId = input.ReadInt64();
            break;
          }
          case 50: {
            if (packetData_ == null) {
              PacketData = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(PacketData);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Error = input.ReadString();
            break;
          }
          case 16: {
            ToPlayerId = input.ReadInt64();
            break;
          }
          case 24: {
            PacketCommand = input.ReadInt32();
            break;
          }
          case 32: {
            DirectSendClient = input.ReadBool();
            break;
          }
          case 40: {
            PendingMessageId = input.ReadInt64();
            break;
          }
          case 50: {
            if (packetData_ == null) {
              PacketData = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(PacketData);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 路由转发玩家的公会请求消息
  /// server -> otherserver -> guild
  /// </summary>
  public sealed partial class GuildRoutePlayerMessageReq : pb::IMessage<GuildRoutePlayerMessageReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GuildRoutePlayerMessageReq> _parser = new pb::MessageParser<GuildRoutePlayerMessageReq>(() => new GuildRoutePlayerMessageReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GuildRoutePlayerMessageReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Gserver.RouteReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GuildRoutePlayerMessageReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GuildRoutePlayerMessageReq(GuildRoutePlayerMessageReq other) : this() {
      fromPlayerId_ = other.fromPlayerId_;
      fromGuildId_ = other.fromGuildId_;
      fromServerId_ = other.fromServerId_;
      fromPlayerName_ = other.fromPlayerName_;
      packetCommand_ = other.packetCommand_;
      packetData_ = other.packetData_ != null ? other.packetData_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GuildRoutePlayerMessageReq Clone() {
      return new GuildRoutePlayerMessageReq(this);
    }

    /// <summary>Field number for the "fromPlayerId" field.</summary>
    public const int FromPlayerIdFieldNumber = 1;
    private long fromPlayerId_;
    /// <summary>
    /// 玩家id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long FromPlayerId {
      get { return fromPlayerId_; }
      set {
        fromPlayerId_ = value;
      }
    }

    /// <summary>Field number for the "fromGuildId" field.</summary>
    public const int FromGuildIdFieldNumber = 2;
    private long fromGuildId_;
    /// <summary>
    /// 玩家公会id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long FromGuildId {
      get { return fromGuildId_; }
      set {
        fromGuildId_ = value;
      }
    }

    /// <summary>Field number for the "fromServerId" field.</summary>
    public const int FromServerIdFieldNumber = 3;
    private int fromServerId_;
    /// <summary>
    /// 玩家当前所在服务器id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FromServerId {
      get { return fromServerId_; }
      set {
        fromServerId_ = value;
      }
    }

    /// <summary>Field number for the "fromPlayerName" field.</summary>
    public const int FromPlayerNameFieldNumber = 4;
    private string fromPlayerName_ = "";
    /// <summary>
    /// 玩家名
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FromPlayerName {
      get { return fromPlayerName_; }
      set {
        fromPlayerName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "packetCommand" field.</summary>
    public const int PacketCommandFieldNumber = 5;
    private int packetCommand_;
    /// <summary>
    /// 消息号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PacketCommand {
      get { return packetCommand_; }
      set {
        packetCommand_ = value;
      }
    }

    /// <summary>Field number for the "packetData" field.</summary>
    public const int PacketDataFieldNumber = 6;
    private global::Google.Protobuf.WellKnownTypes.Any packetData_;
    /// <summary>
    /// 消息内容
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Any PacketData {
      get { return packetData_; }
      set {
        packetData_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GuildRoutePlayerMessageReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GuildRoutePlayerMessageReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FromPlayerId != other.FromPlayerId) return false;
      if (FromGuildId != other.FromGuildId) return false;
      if (FromServerId != other.FromServerId) return false;
      if (FromPlayerName != other.FromPlayerName) return false;
      if (PacketCommand != other.PacketCommand) return false;
      if (!object.Equals(PacketData, other.PacketData)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FromPlayerId != 0L) hash ^= FromPlayerId.GetHashCode();
      if (FromGuildId != 0L) hash ^= FromGuildId.GetHashCode();
      if (FromServerId != 0) hash ^= FromServerId.GetHashCode();
      if (FromPlayerName.Length != 0) hash ^= FromPlayerName.GetHashCode();
      if (PacketCommand != 0) hash ^= PacketCommand.GetHashCode();
      if (packetData_ != null) hash ^= PacketData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FromPlayerId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(FromPlayerId);
      }
      if (FromGuildId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(FromGuildId);
      }
      if (FromServerId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(FromServerId);
      }
      if (FromPlayerName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(FromPlayerName);
      }
      if (PacketCommand != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(PacketCommand);
      }
      if (packetData_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(PacketData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FromPlayerId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(FromPlayerId);
      }
      if (FromGuildId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(FromGuildId);
      }
      if (FromServerId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(FromServerId);
      }
      if (FromPlayerName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(FromPlayerName);
      }
      if (PacketCommand != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(PacketCommand);
      }
      if (packetData_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(PacketData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FromPlayerId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(FromPlayerId);
      }
      if (FromGuildId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(FromGuildId);
      }
      if (FromServerId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FromServerId);
      }
      if (FromPlayerName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FromPlayerName);
      }
      if (PacketCommand != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PacketCommand);
      }
      if (packetData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PacketData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GuildRoutePlayerMessageReq other) {
      if (other == null) {
        return;
      }
      if (other.FromPlayerId != 0L) {
        FromPlayerId = other.FromPlayerId;
      }
      if (other.FromGuildId != 0L) {
        FromGuildId = other.FromGuildId;
      }
      if (other.FromServerId != 0) {
        FromServerId = other.FromServerId;
      }
      if (other.FromPlayerName.Length != 0) {
        FromPlayerName = other.FromPlayerName;
      }
      if (other.PacketCommand != 0) {
        PacketCommand = other.PacketCommand;
      }
      if (other.packetData_ != null) {
        if (packetData_ == null) {
          PacketData = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        PacketData.MergeFrom(other.PacketData);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            FromPlayerId = input.ReadInt64();
            break;
          }
          case 16: {
            FromGuildId = input.ReadInt64();
            break;
          }
          case 24: {
            FromServerId = input.ReadInt32();
            break;
          }
          case 34: {
            FromPlayerName = input.ReadString();
            break;
          }
          case 40: {
            PacketCommand = input.ReadInt32();
            break;
          }
          case 50: {
            if (packetData_ == null) {
              PacketData = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(PacketData);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            FromPlayerId = input.ReadInt64();
            break;
          }
          case 16: {
            FromGuildId = input.ReadInt64();
            break;
          }
          case 24: {
            FromServerId = input.ReadInt32();
            break;
          }
          case 34: {
            FromPlayerName = input.ReadString();
            break;
          }
          case 40: {
            PacketCommand = input.ReadInt32();
            break;
          }
          case 50: {
            if (packetData_ == null) {
              PacketData = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(PacketData);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
