using UnityEngine.UI;
//generated by Editor, DONT EDIT!!!
public class TestFormUIElements : UIElements
{
	public Image Image1;
	public Text T2;
	public Button B3;
	public Text PlayerName;
	public Text PlayerLevel;
	public Text PlayerExp;
}